### ISSUE TITLE
Rename organization

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea-test1#1]
Can we rename the organization url to use all lowercase? Many of the orgs I follow use that pattern. The printed name can be whatever we want.

Suggestion:
org/url name: triplea-game
name: TripleA

**Comment by gaborbernat** [comment]
+1 :)

**Comment by DanVanAtta** [comment]
I was debating with myself if we need to call ourselves "tripleA the gameEngine" instead of just "tripleA" or "triple-game." Given that Hasbro once already did give tripleA a cease and desist, and as a part of a compromise the names that needed to change were changed, this means that "tripleA" the name was spared for us to use : )

What also helped convince me that tripleA is a good name is that it turns out there is a CNET page with some really good reviews for tripleA (and a download link! this is something we'll have to try and not break in the future): http://download.cnet.com/TripleA/3000-18516_4-75184098.html


So, long winded +1

**Comment by djensen47** [comment]
I was thinking that I just don't like mixed-case in urls. ;-)

**Comment by djensen47** [comment]
We also need an icon for the organization.

**Comment by veqryn** [comment]
putting in lower case still works: https://github.com/triplea-game

Date: Wed, 15 Jul 2015 17:36:43 -0700

**Comment by djensen47** [comment]
Yeah but the default is mixed case. If you're going to camel case it, I'd at least remove the dash: TripleAGame

So `TripleAGame` or `triplea-game`. :smile:

**Comment by doctored** [comment]
what are the specs for the icon maybe i can helpi still have all the files i used to make the app icon.

:)

**Comment by djensen47** [comment]
The organization owners have to set it. It should be square 300x300 or so.

**Comment by doctored** [comment]
![icon](https://cloud.githubusercontent.com/assets/4541889/8734589/da1b4b60-2bbf-11e5-8283-994191c6a517.png)

let me know if that works!

:)

**Comment by ron-murhammer** [comment]
Icon added. I tend to agree with the lowercase convention. If Veqryn is fine with it then I'll go ahead and rename the org to "triplea-game".

**Comment by djensen47** [comment]
:+1:

**Comment by veqryn** [comment]
done

**Comment by djensen47** [comment]
:+1:
