### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by djensen47** [triplea-game/triplea-test1#4]
Depending on your FOSS politics, GPL can be seen as somewhat toxic. Any software that uses any of the TripleA software must also be open sourced. For instance, I couldn't have a proprietary plugin.

I would like to see if it would be at all possible to switch to an Apache v2 license. It might be next to impossible but might be worth exploring.

**Comment by djensen47** [comment]
It looks like every contributor who contributed code would have to agree to re-lease with a new license.

**Comment by DanVanAtta** [comment]
I was going to propose that we remove the license from the Java file header. It's not necessary to have it there, and naturally it is not consistently at the top of every file.

1. Is there agreement that we can remove the license from the header comments? (I was not going to bring this up in favor of focusing on other things, but seems like we are on the subject).

2. Where should the "master" license live, ie: where is the authoritative source of that info?

3. @djensen47 What happens if some of the contributors can not be reached? TripleA interestingly is a very old code base.

4. @djensen47 Any examples of propriety plugins you can state so we can more context of what we are talking about?

**Comment by djensen47** [comment]
> 3. @djensen47 What happens if some of the contributors can not be reached? TripleA interestingly is a very old code base.

Then you cannot convert it.

> 4. @djensen47 Any examples of propriety plugins you can state so we can more context of what we are talking about?

Maybe an integration with a site like axisandallies.org :wink: There might be proprietary things like an API token. It's not a _great_ example.

It would also allow somebody to write proprietary to to commercialize the app. This may be something the group _does not want_ to do.

**Comment by DanVanAtta** [comment]
You have a lot of people to contact:

`$ git log | grep "^Author" | sort | uniq
Author: aafiend <aafiend@mycompany.com>
Author: ahahibrahim2 <ahahibrahim2@mycompany.com>
Author: bcarothers <bcarothers@mycompany.com>
Author: Chris Duncan <veqryn@hotmail.com>
Author: Chris Duncan <veqryn@mycompany.com>
Author: cmoffitt <cmoffitt@mycompany.com>
Author: comradekev <comradekev@mycompany.com>
Author: ComradeKev <ComradeKev@mycompany.com>
Author: dowobeha <dowobeha@mycompany.com>
Author: george_h <george_h@mycompany.com>
Author: h_mccleave <h_mccleave@mycompany.com>
Author: immerc <immerc@mycompany.com>
Author: kdm98 <kdm98@mycompany.com>
Author: kendric <kendric@mycompany.com>
Author: lnxduk <lnxduk@mycompany.com>
Author: nekromancer <nekromancer@mycompany.com>
Author: no_author <no_author@no_author.com>
Author: rmurhammer <rmurhammer@mycompany.com>
Author: root <root@mycompany.com>
Author: sgbridges <sgbridges@mycompany.com>
Author: suvarov454 <suvarov454@mycompany.com>
Author: tclayton <tclayton@mycompany.com>
Author: veqryn <veqryn@localhost.localdomain>
Author: wanderinghead <wanderinghead@mycompany.com>
Author: wisconsin777 <wisconsin777@mycompany.com>
Author: zoobert <zoobert@mycompany.com>`

Given the number of contributors, is it practical to proceed? I'm assuming all these people actually need to be contacted. From what I can tell there were 3 main developers on the source code, Sean Bridges, Veqryn (and one other person), and Redrum did most of the AI stuff (but perhaps more people there, which is likely where we get the long list from). So, I do wonder if you only need to get the "main" contributors, and how you would define the "main" ones.

**Comment by gaborbernat** [comment]
I for one have no objections against the current license.

**Comment by ron-murhammer** [comment]
Honestly, I don't see this as a major issue and getting it changed would be a huge pain. 

The only thing that would be interesting is the license header comments. I'm not sure if its best to keep that in every file or remove them but its a good point to bring up.

**Comment by DanVanAtta** [comment]
We can put the license in a file perhaps at the root of the project, also reference/include it in the documentation and/or website. I'm open to suggestions on other locations. Otherwise I think we have consensus we can remove it from the top of java class files.

Regrettably it also seems like it'll be a bit of a pain in the butt to contact all contributors to change the license. @djensen47 , is this question good to close?
